version: '3.8'

services:
  web:
    build:
      context: ./
    image: fastapi_bncc_frontend_web
    container_name: web_front
    volumes:
      - ./:/usr/src/app
    ports:
      - 5001:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - PORT=8000